.TH SBCENC 1 "2012-11-15" "1.0" ""

.SH NAME
sbcenc \- SBC decoder utility

.SH SYNOPSIS
.B sbcdec
.RI [options]
.RI file(s)

.SH DESCRIPTION
.B sbcdec
command decode SBC audio file.

.SH OPTIONS:
.TP
.B \\-h, --help
Display help

.TP
.B \\-v, --verbose
Verbose mode

.TP
.B \\-d, --device <dsp>
Sound device

.TP
.B \\-f, --file <file>
Decode to a file

.SH AUTHOR
Marcel Holtmann <marcel@holtmann.org>

.PP
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>,
for the Debian project (but may be used by others).
