.TH SBCINFO 1 "2012-11-15" "1.0" ""

.SH NAME
sbcinfo \- subband codec (SBC) analyzer

.SH SYNOPSIS
.B sbcinfo
.RI <file>

.SH DESCRIPTION
.B sbcinfo
command reads SBC audio file and prints information about audio format used.

.SH AUTHOR
Marcel Holtmann <marcel@holtmann.org>

.PP
This manual page was written by Krzysztof Burghardt <krzysztof@burghardt.pl>,
for the Debian project (but may be used by others).
